name: weather_app
description: "A Weather app mini project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^10.0.1 # Auto Route
  dio: ^5.8.0+1 # Network
  envied: ^1.1.1 # Environment Variables
  flex_color_scheme: ^8.1.1 # Color Scheme
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2 # Hooks
  flutter_screenutil: ^5.9.3 # Screen Util
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1 # Functional Programming
  freezed_annotation: ^2.4.4 # Freezed
  hooks_riverpod: ^2.6.1 # Riverpod
  intl: ^0.20.2
  json_annotation: ^4.9.0 # JSON Serialization
  logger: ^2.5.0 # Logger
  skeletonizer: ^1.4.3 # Skeleton Loader

dev_dependencies:
  auto_route_generator: null # Auto Route Generator
  build_runner: ^2.4.15 # Build Runner
  custom_lint: ^0.7.0 # Custom Lint
  envied_generator: ^1.1.1 # Environment Variables Generator
  flutter_gen_runner: ^5.5.0+1 # Flutter Gen Runner
  flutter_lints: ^5.0.0 # Flutter Lints
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8 # Freezed
  json_serializable: ^6.9.4 # JSON Serialization
  lint: ^2.3.0 # Lint
  riverpod_lint: ^2.6.2 # Riverpod Lint
  mockito: ^5.4.5 # Mocking

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/svg/
    - assets/icons/svg/night/
    - assets/icons/svg/day/

  fonts:
    - family: MonaSans
      fonts:
        - asset: assets/fonts/MonaSans-Black.otf
          weight: 900
        - asset: assets/fonts/MonaSans-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/MonaSans-Bold.otf
          weight: 700
        - asset: assets/fonts/MonaSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/MonaSans-Medium.otf
          weight: 500
        - asset: assets/fonts/MonaSans-Regular.otf
          weight: 400
        - asset: assets/fonts/MonaSans-Light.otf
          weight: 300
        - asset: assets/fonts/MonaSans-ExtraLight.otf
          weight: 200
